# 02 JAN 2022 TRAN MINH HAI
# first template to create a S3 bucket
AWSTemplateFormatVersion: "2010-09-09"
Description: Create a S3 bucket
Resources:
  TestCreateS3BucketWithCloudFormation:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TestCreateS3BucketWithCloudFormation
      PolicyDocument:
        Id: MyPolicyForS3StaticWeb
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref TestCreateS3BucketWithCloudFormation
                - /*
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - TestCreateS3BucketWithCloudFormation
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt
          - TestCreateS3BucketWithCloudFormation
          - DomainName
    Description: Name of S3 bucket to hold website content
